# -*- coding: utf-8 -*-
"""Website Traffic Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYlfWn_9NXvLIfpdn7rfUrGKd9ZdthVp
"""

# ==========================================
# PROJECT 3: WEBSITE TRAFFIC ANALYSIS
# Phase 1 - Import Libraries
# ==========================================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns
pd.set_option("display.max_columns", None)

# Plot style
sns.set_style("whitegrid")

print("Libraries Imported Successfully!")

# ==========================================
# Load Dataset
# ==========================================

df = pd.read_csv("/content/traffic.csv")

print("Dataset Loaded Successfully!")

# Display first five rows

df.head()

df.tail()

print("Dataset Shape:", df.shape)

print(df.columns)

df.info()

df.describe(include="all")

df.sample(10)

df.dtypes

for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

missing = df.isnull().sum()

missing = missing[missing > 0]

print(missing)

# ==========================================
# Fill Missing Values
# ==========================================

# Fill categorical columns with "Unknown"

categorical_cols = ['country', 'city', 'artist', 'album', 'track', 'isrc', 'linkid']

for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")

print("Missing Values After Cleaning:")
print(df.isnull().sum())

# ==========================================
# Duplicate Records
# ==========================================

print("Duplicate Records:", df.duplicated().sum())

# ==========================================
# Remove Duplicate Records
# ==========================================

df.drop_duplicates(inplace=True)

print("Dataset Shape:", df.shape)

print("Duplicate Records:", df.duplicated().sum())

# ==========================================
# Convert Date
# ==========================================

df["date"] = pd.to_datetime(df["date"])

print(df["date"].dtype)

print("Start Date :", df["date"].min())

print("End Date :", df["date"].max())

df.dtypes

# ==========================================
# Clean Text Columns
# ==========================================

text_columns = [
    "country",
    "city",
    "artist",
    "album",
    "track"
]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

print("Text Cleaning Completed!")

print(df.isnull().sum())

df.info()

print("Dataset Shape:", df.shape)

# ==========================================
# Save Cleaned Dataset
# ==========================================

df.to_csv(
    "cleaned website traffic dataset.csv",
    index=False
)

print("Cleaned Dataset Saved Successfully!")

df.head()

# ==========================================
# Feature Engineering
# Create Year
# ==========================================

df["Year"] = df["date"].dt.year

df[["date", "Year"]].head()

# Create Month Number

df["Month"] = df["date"].dt.month

df[["date", "Month"]].head()

# Create Month Name

df["Month_Name"] = df["date"].dt.month_name()

df[["date", "Month_Name"]].head()

# Create Day

df["Day"] = df["date"].dt.day

df[["date", "Day"]].head()

# Create Day Name

df["Day_Name"] = df["date"].dt.day_name()

df[["date", "Day_Name"]].head()

# Weekend or Weekday

df["Week_Type"] = np.where(
    df["Day_Name"].isin(["Saturday", "Sunday"]),
    "Weekend",
    "Weekday"
)

df["Week_Type"].value_counts()

# Event Category

df["Event_Category"] = df["event"].str.title()

df["Event_Category"].value_counts()

# Top Country Flag

top_countries = df["country"].value_counts().head(10).index

df["Top_Country"] = np.where(
    df["country"].isin(top_countries),
    "Top Country",
    "Other"
)

df["Top_Country"].value_counts()

# Top Artist Flag

top_artists = df["artist"].value_counts().head(10).index

df["Top_Artist"] = np.where(
    df["artist"].isin(top_artists),
    "Top Artist",
    "Other"
)

df["Top_Artist"].value_counts()

# Top Album Flag

top_albums = df["album"].value_counts().head(10).index

df["Top_Album"] = np.where(
    df["album"].isin(top_albums),
    "Top Album",
    "Other"
)

df["Top_Album"].value_counts()

# Traffic Category based on Event

traffic_mapping = {
    "pageview": "Viewed",
    "click": "Clicked",
    "preview": "Previewed"
}

df["Traffic_Category"] = (
    df["event"]
    .str.lower()
    .map(traffic_mapping)
    .fillna("Other")
)

df["Traffic_Category"].value_counts()

print(df.columns)

# Save Feature Engineered Dataset

df.to_csv(
    "website traffic feature engineered.csv",
    index=False
)

print("Feature Engineered Dataset Saved Successfully!")

df.head()

# Chart 1: Event Distribution

plt.figure(figsize=(8,6))

sns.countplot(
    data=df,
    x="event",
    palette="viridis"
)

plt.title("Website Event Distribution", fontsize=16)
plt.xlabel("Event Type")
plt.ylabel("Count")

plt.tight_layout()

plt.savefig("Website Event Distribution.png", dpi=300)

plt.show()

# Chart 2: Daily Website Traffic

daily = df.groupby("Day").size()

plt.figure(figsize=(12,6))

plt.plot(
    daily.index,
    daily.values,
    marker="o"
)

plt.title("Daily Website Traffic", fontsize=16)
plt.xlabel("Day")
plt.ylabel("Number of Events")

plt.tight_layout()

plt.savefig("Daily Website Traffic.png", dpi=300)

plt.show()

# Chart 3: Monthly Website Traffic

monthly = (
    df.groupby("Month_Name")
      .size()
      .reindex([
          "January","February","March","April","May","June",
          "July","August","September","October","November","December"
      ])
)

plt.figure(figsize=(12,6))

sns.barplot(
    x=monthly.index,
    y=monthly.values,
    palette="rocket"
)

plt.xticks(rotation=45)

plt.title("Monthly Website Traffic", fontsize=16)

plt.tight_layout()

plt.savefig("Monthly Website Traffic.png", dpi=300)

plt.show()

# Chart 4: Top Countries

country = df["country"].value_counts().head(10)

plt.figure(figsize=(10,6))

sns.barplot(
    x=country.values,
    y=country.index,
    palette="mako"
)

plt.title("Top 10 Countries by Website Traffic", fontsize=16)

plt.tight_layout()

plt.savefig("Top 10 Countries.png", dpi=300)

plt.show()

# Chart 5: Top Cities

city = df["city"].value_counts().head(10)

plt.figure(figsize=(10,6))

sns.barplot(
    x=city.values,
    y=city.index,
    palette="flare"
)

plt.title("Top 10 Cities by Website Traffic", fontsize=16)

plt.tight_layout()

plt.savefig("Top 10 Cities.png", dpi=300)

plt.show()

# Chart 6: Top Artists

artist = df["artist"].value_counts().head(10)

plt.figure(figsize=(10,6))

sns.barplot(
    x=artist.values,
    y=artist.index,
    palette="crest"
)

plt.title("Top 10 Artists", fontsize=16)

plt.tight_layout()

plt.savefig("Top 10 Artists.png", dpi=300)

plt.show()

# Chart 7: Top Albums

album = df["album"].value_counts().head(10)

plt.figure(figsize=(10,6))

sns.barplot(
    x=album.values,
    y=album.index,
    palette="coolwarm"
)

plt.title("Top 10 Albums", fontsize=16)

plt.tight_layout()

plt.savefig("Top 10 Albums.png", dpi=300)

plt.show()

# Chart 8: Top 10 Tracks

track = df["track"].value_counts().head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    x=track.values,
    y=track.index,
    palette="viridis"
)

plt.title("Top 10 Tracks by Website Traffic", fontsize=16)

plt.tight_layout()

plt.savefig("Top 10 Tracks.png", dpi=300)

plt.show()

# Chart 9: Top 10 Link IDs

link = df["linkid"].value_counts().head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    x=link.values,
    y=link.index,
    palette="rocket"
)

plt.title("Top 10 Link IDs", fontsize=16)

plt.tight_layout()

plt.savefig("Top 10 Link IDs.png", dpi=300)

plt.show()

# Chart 10: Weekday vs Weekend Traffic

week = df["Week_Type"].value_counts()

plt.figure(figsize=(7,5))

sns.barplot(
    x=week.index,
    y=week.values,
    palette="Set2"
)

plt.title("Weekday vs Weekend Website Traffic", fontsize=16)

plt.xlabel("Week Type")
plt.ylabel("Traffic Count")

plt.tight_layout()

plt.savefig("Weekday vs Weekend Traffic.png", dpi=300)

plt.show()

# Chart 11: Country-wise Traffic Share

country = df["country"].value_counts().head(10)

plt.figure(figsize=(8,8))

plt.pie(
    country.values,
    labels=country.index,
    autopct="%1.1f%%",
    startangle=90
)

plt.title("Top 10 Country-wise Traffic Share")

plt.savefig("Country-wise Traffic Share.png", dpi=300)

plt.show()

# Chart 12: Event Trend Over Time

trend = df.groupby("date").size()

plt.figure(figsize=(14,6))

plt.plot(
    trend.index,
    trend.values
)

plt.title("Website Traffic Trend Over Time", fontsize=16)

plt.xlabel("Date")
plt.ylabel("Traffic")

plt.tight_layout()

plt.savefig("Website Traffic Trend.png", dpi=300)

plt.show()

# Chart 13: Top ISRC Codes

isrc = df["isrc"].value_counts().head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    x=isrc.values,
    y=isrc.index,
    palette="mako"
)

plt.title("Top 10 ISRC Codes", fontsize=16)

plt.tight_layout()

plt.savefig("Top 10 ISRC Codes.png", dpi=300)

plt.show()

# Chart 14: Artist Traffic Distribution

artist = df["artist"].value_counts().head(15)

plt.figure(figsize=(10,8))

sns.barplot(
    x=artist.index,
    y=artist.values,
    palette="crest"
)

plt.xticks(rotation=90)

plt.title("Artist Traffic Distribution", fontsize=16)

plt.tight_layout()

plt.savefig("Artist Traffic Distribution.png", dpi=300)

plt.show()

# Chart 15: Album Traffic Distribution

album = df["album"].value_counts().head(15)

plt.figure(figsize=(12,6))

sns.barplot(
    x=album.index,
    y=album.values,
    palette="flare"
)

plt.xticks(rotation=90)

plt.title("Album Traffic Distribution", fontsize=16)

plt.tight_layout()

plt.savefig("Album Traffic Distribution.png", dpi=300)

plt.show()

# Chart 16: Event-wise Country Analysis

country_event = pd.crosstab(df["country"], df["event"]).head(10)

country_event.plot(
    kind="bar",
    figsize=(12,6)
)

plt.title("Event-wise Country Analysis", fontsize=16)

plt.tight_layout()

plt.savefig("Event-wise Country Analysis.png", dpi=300)

plt.show()

# Chart 17: Monthly Traffic Trend

month = df.groupby("Month_Name").size()

month = month.reindex([
    "January","February","March","April","May","June",
    "July","August","September","October","November","December"
])

plt.figure(figsize=(12,6))

plt.plot(
    month.index,
    month.values,
    marker="o"
)

plt.xticks(rotation=45)

plt.title("Monthly Website Traffic Trend", fontsize=16)

plt.tight_layout()

plt.savefig("Monthly Website Traffic Trend.png", dpi=300)

plt.show()

# Chart 18: Daily Event Heatmap

heat = pd.crosstab(
    df["Day_Name"],
    df["event"]
)

plt.figure(figsize=(8,6))

sns.heatmap(
    heat,
    annot=True,
    cmap="YlGnBu",
    fmt="d"
)

plt.title("Daily Event Heatmap", fontsize=16)

plt.tight_layout()

plt.savefig("Daily Event Heatmap.png", dpi=300)

plt.show()

# Chart 19: Traffic by Top Country

country = df["Top_Country"].value_counts()

plt.figure(figsize=(7,5))

sns.barplot(
    x=country.index,
    y=country.values,
    palette="viridis"
)

plt.title("Traffic by Top Country", fontsize=16)

plt.tight_layout()

plt.savefig("Traffic by Top Country.png", dpi=300)

plt.show()

# Chart 20: Traffic by Top Artist

artist = df["Top_Artist"].value_counts()

plt.figure(figsize=(7,5))

sns.barplot(
    x=artist.index,
    y=artist.values,
    palette="Set2"
)

plt.title("Traffic by Top Artist", fontsize=16)

plt.tight_layout()

plt.savefig("Traffic by Top Artist.png", dpi=300)

plt.show()

# Chart 21: Event Category Distribution

event_cat = df["Traffic_Category"].value_counts()

plt.figure(figsize=(7,5))

sns.barplot(
    x=event_cat.index,
    y=event_cat.values,
    palette="coolwarm"
)

plt.title("Traffic Category Distribution", fontsize=16)

plt.tight_layout()

plt.savefig("Traffic Category Distribution.png", dpi=300)

plt.show()

# Chart 22: Top 10 Countries and Events Heatmap

top10 = df["country"].value_counts().head(10).index

heat2 = pd.crosstab(
    df[df["country"].isin(top10)]["country"],
    df[df["country"].isin(top10)]["event"]
)

plt.figure(figsize=(8,6))

sns.heatmap(
    heat2,
    annot=True,
    cmap="rocket",
    fmt="d"
)

plt.title("Top Countries vs Events", fontsize=16)

plt.tight_layout()

plt.savefig("Top Countries vs Events Heatmap.png", dpi=300)

plt.show()

# Total Website Events

total_events = len(df)

print("Total Website Events:", total_events)

# Total Countries

total_countries = df["country"].nunique()

print("Total Countries:", total_countries)

# Total Cities

total_cities = df["city"].nunique()

print("Total Cities:", total_cities)

# Total Artists

total_artists = df["artist"].nunique()

print("Total Artists:", total_artists)

# Total Albums

total_albums = df["album"].nunique()

print("Total Albums:", total_albums)

# Total Tracks

total_tracks = df["track"].nunique()

print("Total Tracks:", total_tracks)

# Most Popular Event

popular_event = df["event"].mode()[0]

popular_event_count = df["event"].value_counts().iloc[0]

print("Most Popular Event:", popular_event)
print("Event Count:", popular_event_count)

# Most Active Country

top_country = df["country"].mode()[0]

top_country_count = df["country"].value_counts().iloc[0]

print("Most Active Country:", top_country)
print("Traffic:", top_country_count)

# Most Active City

top_city = df["city"].mode()[0]

top_city_count = df["city"].value_counts().iloc[0]

print("Most Active City:", top_city)
print("Traffic:", top_city_count)

# Top Artist

top_artist = df["artist"].mode()[0]

top_artist_count = df["artist"].value_counts().iloc[0]

print("Top Artist:", top_artist)
print("Traffic:", top_artist_count)

# Top Album

top_album = df["album"].mode()[0]

top_album_count = df["album"].value_counts().iloc[0]

print("Top Album:", top_album)
print("Traffic:", top_album_count)

# KPI Summary

kpi_summary = pd.DataFrame({

    "KPI":[

        "Total Website Events",
        "Total Countries",
        "Total Cities",
        "Total Artists",
        "Total Albums",
        "Total Tracks",
        "Most Popular Event",
        "Most Active Country",
        "Most Active City",
        "Top Artist",
        "Top Album"

    ],

    "Value":[

        total_events,
        total_countries,
        total_cities,
        total_artists,
        total_albums,
        total_tracks,
        popular_event,
        top_country,
        top_city,
        top_artist,
        top_album

    ]

})

kpi_summary

# Save KPI Summary

kpi_summary.to_csv(
    "Website Traffic KPI Summary.csv",
    index=False
)

print("KPI Summary Saved Successfully!")

# KPI Dashboard

dashboard = pd.DataFrame({

    "Metric":[
        "Countries",
        "Cities",
        "Artists",
        "Albums",
        "Tracks"
    ],

    "Count":[
        total_countries,
        total_cities,
        total_artists,
        total_albums,
        total_tracks
    ]

})

plt.figure(figsize=(10,6))

sns.barplot(
    data=dashboard,
    x="Metric",
    y="Count",
    palette="viridis"
)

plt.title("Website Traffic KPI Dashboard", fontsize=16)

plt.tight_layout()

plt.savefig(
    "Website Traffic KPI Dashboard.png",
    dpi=300
)

plt.show()